### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by olibclarke** [mxhulab/cryosieve#19]
Hi,

I've read the CryoSieve paper and am keen to try the software - fantastic work! I have a couple of queries regarding the results in the paper and applications:

1. In the paper, the hemagglutinin map seems significantly improved after CryoSieve. This dataset has a quite severe orientation bias. Was the sphericity or other measures of anisotropy improved after CryoSieve?

2. Have you tried CryoSieve for any cases where there is true compositional/conformational heterogeneity? I worry that in this case, if a minor state is significantly different to the consensus reconstruction, it may be lost during the sieving process. Have you tested this, or would you recommend only using CryoSieve on a final stack (after classification).

**Comment by jianyingzhu** [comment]
Hi,
Thank you for your attention to CryoSieve. Our experience is as follows:

1. We compared the angle distribution reported by CryoSPARC before and after CryoSieve (in Supplementary Figure 6 of the paper) and did not find significant differences. So we expect the sphericity or other measures of anisotropy to be similar before and after CryoSieve.
2. That's a good question. Our experiments did not include such examples, and we are preparing to test such instances, hoping to discover new potential applications. We anticipate that CryoSieve will maintain particles corresponding to the dominant conformations in the original dataset. However, particles discarded by CryoSieve might not be useless; they could belong to other conformations. If the aim is to enhance the resolution of the main conformation, perhaps CryoSieve could be used on the final stack. However, if the goal is to identify heterogeneity, this would require further exploration.

**Comment by Zarrathustra** [comment]
In addition to the earlier comment regarding the second point, I would like to make an additional observation. The manuscript implies that particles belonging to rare conformations should be sieved out, resulting in the retained particles representing a single state. However, at present, there is no direct and sufficient evidence to support this assumption, although it seems intuitively plausible. If we accept this premise as true, then it follows that the particles representing rare conformations would be found in the sieved-out particles, saved in the _iterXXX_sieved.star files. These particles may represent a diverse set of states and, importantly, might not be influenced by the dominant conformation's attraction effect. Therefore, analyzing the sieved-out particles could potentially reveal rare conformational states. While strong evidence for this hypothesis is currently lacking, pursuing this line of inquiry could yield intriguing results and significantly advance our understanding of these rare states.

**Comment by olibclarke** [comment]
Thank you both very much for the thoughtful replies! I will try CryoSieve then and see how it behaves with heterogeneous data!
