### ISSUE TITLE
cryosieve toy dataset -   raise ValueError('Invalid particle star file.') ValueError: Invalid particle star file.

### ISSUE THREAD

**Issue by jasonkey** [mxhulab/cryosieve#20]
Hi, 

I've installed cryosieve as described and I can run the `cryosieve -h` command and get the expected help message. 
When I attempt to run the example on the "toy" dataset, I see: 

```
cryosieve-core --i CNG.star --o output_CNG.star --angpix 1.32 --volume CNG_A.mrc --volume CNG_B.mrc --mask CNG_mask.mrc --retention_ratio 0.8 --frequency 40 --directory ./

Traceback (most recent call last):
  File "/programs/x86_64-linux/cryosieve/1.2.3/bin/cryosieve-core", line 10, in <module>
    sys.exit(core())
  File "/programs/x86_64-linux/cryosieve/1.2.3/miniconda3/lib/python3.10/site-packages/cryosieve/core.py", line 82, in core
    main(args)
  File "/programs/x86_64-linux/cryosieve/1.2.3/miniconda3/lib/python3.10/site-packages/cryosieve/core.py", line 35, in main
    dataset     = ParticleDataset(args.i, args.directory, args.angpix)
  File "/programs/x86_64-linux/cryosieve/1.2.3/miniconda3/lib/python3.10/site-packages/cryosieve/ParticleDataset.py", line 56, in __init__
    raise ValueError('Invalid particle star file.')
ValueError: Invalid particle star file.

```

The CNG.star file looks at first glance to be correct, i.e. it is a star file and references the CNG_particles.mrcs file which is present. Any advice here would be appreciated. Thanks

**Comment by Zarrathustra** [comment]
Hi, please check whether this command is executed in the same folder as the CNG.star locates.

**Comment by jasonkey** [comment]
Hi, 

Thanks for the reply - yes, I am running the command from the "toys" directory and I can confirm that the software is actually reading the star file. 

Just so we're on the same page, here's the md5sums for the files I pulled w/ git lfs : 
```
15386b4ff96875be4c9681f326a0150a  CNG_A.mrc
d70d7216a8bd136732affebbffdce1d4  CNG_B.mrc
119ed6b9ecd5c69d8d6c33318615580d  CNG_mask.mrc
95531604e8d687268aa341f753a2702c  CNG_particles.mrcs
ecbeff828800facbffd82119fb583eaa  CNG.star
416bbc5c11828562ef6e65584bfdd30e  README.md
133dc9919369c1bc8810b872955402b3  run.slurm
```

Assuming this star file is correct, the issue may be in the logic around line 25 of  cryosieve/ParticleDataset.py. The conditionals there should sort out what type of star file this is but they don't match the star file provided. 

Specifically for
```
 if len(star) == 1 and (0 in star or 'images' in star):
```

len(star) for the file in this example is 1 but the second "'images' in star" does not match so we fall through to raise ValueError('Invalid particle star file.')

**Comment by zerinf** [comment]
Hi, thank you for reporting the issue. The bug you encountered is caused by a change in the behavior of starfile versions higher than 0.5, specifically related to reading star files containing data blocks with empty name.

We apologize for any inconvenience this may have caused. We are aware of the issue and are working on a solution. In the upcoming minor release of CryoSieve, we will reinforce the dependency on starfile versions less than 0.5 to ensure compatibility.

To quickly skip the bug, you can use `pip install starfile==0.4.12` to install a lower version stafile.

**Comment by jasonkey** [comment]
Thanks for the advice - downgrading starfile to 0.4.12 seems to do the trick. Now the "toy" example processes to completion. We can close this issue.

**Comment by Zarrathustra** [comment]
CryoSieve version 1.2.4 is now released. It should address this issue.
