### ISSUE TITLE
libaray doesn't match

### ISSUE THREAD

**Issue by fengwang1988** [mxhulab/cryosieve#28]
Hi 
i solved the issue and install cryosieve sucessfully. Then I used the suggested command to run the toy, while it reports the error "Traceback (most recent call last):
  File "path/miniconda/envs/CRYOSIEVE_ENV/bin/cryosieve-core", line 10, in <module>
    sys.exit(core())
  File "path/miniconda/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/cryosieve/core.py", line 97, in core
    main(args)
  File "path/Soft/miniconda/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/cryosieve/core.py", line 45, in main
    dataset     = ParticleDataset(args.i, args.directory, args.angpix)
  File "path/miniconda/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/cryosieve/ParticleDataset.py", line 57, in __init__
    raise ValueError('Invalid particle star file.')
ValueError: Invalid particle star file. "
I ignore this and run my own dataset, while it runs ok at first iteration "[ITER 0][Overall Retaining ratio: 100.00%][Threshold frequency : 40.00A]", but later it also reports the error "mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
	Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it."
Could you help me to solve these issues? Thanks a lot. 

Best,

Feng

**Comment by zerinf** [comment]
Hi Feng,

We have encountered a similar error while running PyTorch's distributed training, and we believe we can provide some guidance to help you resolve it. Before running CryoSieve, please try executing the following commands:
```
export OMP_NUM_THREADS=1
export MKL_THREADING_LAYER=GNU
```

**Comment by mxhulab** [comment]
Hi Feng, it seems there is a conflict between two threading methods (GNU_THREADING and MKL_THREADING) in your system, and they are not compatible with each other. Please try the method that @zerinf mentioned.

**Comment by mxhulab** [comment]
@fengwang1988 Hope that your issue has been addressed. We have updated the FAQ section on the homepage to reflect this.
