### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'balance'

### ISSUE THREAD

**Issue by Henry-946** [mxhulab/cryosieve#32]
Hi Mingxu, I am trying to run the cryosieve, but encountered with an error, pls see the full log I have, any suggestions are appreciated, many thanks!

(CRYOSIEVE_ENV) [fengwei.zheng@compute089 0_sieve]$ cryosieve --reconstruct_software "mpirun -n 8 relion_reconstruct_mpi" --postprocess_software relion_postprocess --i j159_md3.star --o output/ --mask J159_004_volume_mask_refine.mrc --angpix 0.828 --num_iters 10 --frequency_start 40 --frequency_end 3 --retention_ratio 0.8 --sym C1 --num_gpus 4 --balance
The `--postprocess_software` will be deprecated soon. CryoSieve will implement its own postprocessing.
[ITER 0][Overall Retaining ratio: 100.00%][Threshold frequency : 40.00A]
[Subprocesses completed successfully in 173.95s.][RECONSTRUCT_DONE, ITERATION 0]
[Subprocesses completed successfully in 17.64s.][POSTPROCESS_DONE, ITERATION 0]
Traceback (most recent call last):
  File "/home/fengwei.zheng/1-install/miniconda3/envs/CRYOSIEVE_ENV/bin/cryosieve-core", line 8, in <module>
    sys.exit(core())
  File "/home/fengwei.zheng/1-install/miniconda3/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/cryosieve/core.py", line 92, in core
    core_args = f'--i {args.i} --o {args.o} {f"--directory {args.directory}" if args.directory else ""} --angpix {args.angpix} {" ".join([f"--volume {volume}" for volume in args.volume])} {f"--mask {args.mask}" if args.mask is not None else ""} --retention_ratio {args.retention_ratio} --frequency {args.frequency} {"--balance" if args.balance else ""}'
AttributeError: 'Namespace' object has no attribute 'balance'
[Subprocesses reported an error. Return code: [1].][SIEVE_DONE, ITERATION 0]

**Comment by Zarrathustra** [comment]
Thank you for your feedback. We have this bug was introduced in version 1.2.6. And now will update this software to v1.2.8, to get it fixed.

**Comment by Henry-946** [comment]
Thank you so much for your prompt fixing, appreciate that!
