### ISSUE TITLE
Low memory usage

### ISSUE THREAD

**Issue by Henry-946** [mxhulab/cryosieve#34]
Dear CryoSieve developers,

I am trying to run the cryosieve on my dataset with about 520K particles, and noticed that the GPU memory usage is low, not sure if we can take like ~80% usage of the computing resource to make it faster, pls see my log below:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:04:00.0 Off |                  N/A |
| 20%   52C    P2   195W / 250W |   1548MiB / 11264MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:09:00.0 Off |                  N/A |
| 21%   34C    P2   177W / 250W |   1548MiB / 11264MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  Off  | 00000000:84:00.0 Off |                  N/A |
| 20%   36C    P2   174W / 250W |   1552MiB / 11264MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  Off  | 00000000:87:00.0 Off |                  N/A |
| 20%   34C    P2   174W / 250W |   1548MiB / 11264MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
 
I have test to set the export OMP_NUM_THREADS=2 or 8, seems the VRAM usage remains very low~ 
Any suggestions on this? Appreciate!

Best,

Fengwei

**Comment by zerinf** [comment]
Hello Fengwei,

The major time-consuming steps in CryoSieve currently is the 3D-reconstruction process performed by RELION, which is limited to a CPU version. To enhance performance, you can leverage the `--reconstruct_software "mpirun -n 5 relion_reconstruct_mpi"` option to invoke the multi-process versions. This adjustment is expected to boost the overall performance of the reconstruction step.

Regarding the sieving process implemented in GPU code, we have optimized the memory usage on the GPU by employing batch-by-batch techniques. Increasing the batch size might not necessarily lead to improved performance as we have identified the primary bottleneck to be I/O operations——the computation of CryoSieve's score is faster than the data transfer from disk to GPU. Nonetheless, to further enhance performance, you can utilize `--gpus 4` to parallelize the computation of all scores across multiple GPUs. Our testing indicates that employing 4 GPUs can reduce the running time to one-third of the original duration of sieving process.

**Comment by Henry-946** [comment]
Thank you for your detailed explanation, got it, many thanks!

Best,
Fengwei
