### ISSUE TITLE
Toy example fail with 1.2.8

### ISSUE THREAD

**Issue by james-vincent** [mxhulab/cryosieve#36]
Using version 1.2.8 and running this command on the toy dataset:

cryosieve-core --i CNG.star --o my_CNG_1.star --angpix 1.32 --volume CNG_A.mrc --volume CNG_B.mrc --mask CNG_mask.mrc --retention
_ratio 0.8 --frequency 40

I get this error:

python3.10/site-packages/cryosieve/core.py", line 45, in main
    dataset     = ParticleDataset(args.i, args.directory, args.angpix)
NameError: name 'ParticleDataset' is not defined

It works fine with version 1.2.5.  It looks like I am maybe missing some part of the installation but I can't tell what.

In 1.2.5 I find:
python3.10/site-packages/cryosieve/ParticleDataset.py
python3.10/site-packages/cryosieve/__pycache__/ParticleDataset.cpython-310.pyc

but in 1.2.8 only:

python3.10/site-packages/cryosieve/ParticleDataset.py

**Comment by james-vincent** [comment]
It was an installation error.

**Comment by zerinf** [comment]
Hello James-Vincent, thank you for your support. If you have any further questions or encounter any additional bugs during the update and installation process, please feel free to ask here.
