### ISSUE TITLE
 the install of CuPy and PyTorch 

### ISSUE THREAD

**Issue by niejiawei19** [mxhulab/cryosieve#38]
When installing CuPy and PyTorch, it is essential to ensure that their CUDA versions match the CUDA toolkit version installed on your system (which can be checked using nvcc -V). However, my nvidia-smi command might show a different GPU driver version, it shows the maximum CUDA version supported by my GPU.

**Comment by zerinf** [comment]
Hello niejiawei19, I would recommend using the CUDA version obtained from nvidia-smi rather than nvcc -V.
